### ISSUE TITLE
Preparing Individual Milestone 1 Report

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#314]
I will complete the following parts:
- [x] Name
- [x] Group
- [x] Overall description of the responsibilities that are assigned to me
- [x] Overall description of my contributions to the project until Customer Demo 1 on 16.11.2021
- [x] My issues that contribute to the code base demonstrated during the demo
- [x] My issues that contribute to the management of our software project
- [x] My pull requests
- [x] Additional information about my contributions (optional)
- [x] Other comments (optional)

**Comment by zudiay** [comment]
I completed the personal report. I will complete my submission
