### ISSUE TITLE
Preparing Individual Milestone 2 Report

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#450]
I will complete the following parts:

- [x] Software Development Activities
- [x] Unit Tests
- [x] Effort
- [x] Additional Comments

**Comment by zudiay** [comment]
For Software Development Activities part, I will report the following activities:
- [ ] Logical Input Checks on Register & Login & Forgot Password Pages
- [ ] Terms & Conditions
- [ ] Profile Page
- [ ] Authorization
- [ ] Frontend-Backend Connection
- [ ] Bugfixes

**Comment by zudiay** [comment]
I finished the individual report. I will submit it after final checks
