### ISSUE TITLE
Write individual milestone 2 report

### ISSUE THREAD

**Issue by umutgun17** [bounswe/2021SpringGroup5#466]
I will write individual milestone 2 report

- [x] Software Development Activities
- [x] Unit Tests
- [x] Effort
- [x] Additional Comments

**Comment by umutgun17** [comment]
For Software Development Activities part

- [ ]  Creation Event Post Page
- [ ]  Event Detail Page
- [ ]  Comment Feature
- [ ]  Fixed Bugs & Minor Improvements

**Comment by umutgun17** [comment]
I wrote all of them and I submitte it from moodle.
