### ISSUE TITLE
Fixing Frontend Bugs from Milestone 2

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#597]
There remains 3 bugs from the previous milestone.

- [ ] On register page step 2, the error messages are not fully visible because I implemented the error messages and terms and conditions features separately and when we merged them both to master, it caused overflow.
- [ ] Register page tests fail after the merge of terms and conditions feature.
- [ ] Register service function builds the json wrong
