### ISSUE TITLE
Preparing Individual Milestone 3 Report

### ISSUE THREAD

**Issue by zudiay** [bounswe/2021SpringGroup5#665]
I will provide the following:

- [x] Software Development Activities
- [x] Unit Tests
- [x] Weekly Efforts
- [x] Additional Comments

**Comment by zudiay** [comment]
The software development activities part will contain:

- [ ] Implementing functionality on frontend
- [ ] Implementing Participant Listing on Frontend 
- [ ] Implementing Follow Functionality in Frontend
- [ ] Fixing Frontend Bugs from Milestone 2
- [ ] Reviewing PRs
- [ ] Solving Token Issue Between Frontend and Backend
- [ ] Connecting Frontend App to Backend 
- [ ] Making Final Fixes on Frontend
